from .checkcast import *
from .getfield import *
from .getstatic import *
from .instanceof import *
from .new import *
from .putfield import *
from .putstatic import *
from .invokespecial import *
from .invokevirtual import *